const core = require('@actions/core')
const { runStepsEvaluator, mapValuesTestSuite, generateEvaluations } = require('../controller/evaluator.js')

describe('Evaluator', () => {

  describe('mapped structured', () => {
    test('validate mapped structured expected for generate JSON', () => {
      let input = {
        testsuite: {
          '$': {
            name: 'com.example.myapplication_teste.ExampleUnitTest',
            tests: '3',
            skipped: '0',
            failures: '1',
            errors: '0',
            timestamp: '2022-03-24T12:41:39',
            hostname: 'vostro',
            time: '0.007'
          },
          properties: [ '' ],
          testcase: [],
          'system-out': [ '' ],
          'system-err': [ '' ]
        }
      }
      expect(mapValuesTestSuite(input)).toEqual({'errors': '0', 'failures': '1', 'hostname': 'vostro', 'name': 'com.example.myapplication_teste.ExampleUnitTest', 'skipped': '0', 'testcase': [], 'tests': '3', 'time': '0.007', 'timestamp': '2022-03-24T12:41:39'})

    })

    test('testsuite without testcase node (crashed run) must map to an empty testcase list instead of throwing TypeError', () => {
      let input = {
        testsuite: {
          '$': {
            name: 'com.example.trybevirtualmenu.MainActivityTest',
            tests: '0',
            skipped: '0',
            failures: '0',
            errors: '0',
            timestamp: '2026-01-17T16:40:24',
            hostname: 'localhost',
            time: '0.0'
          },
          properties: [ '' ]
        }
      }
      expect(mapValuesTestSuite(input).testcase).toEqual([])
    })

    test('xml without testsuite node must throw a clear error', () => {
      expect(() => mapValuesTestSuite({})).toThrow('formato inesperado')
      expect(() => mapValuesTestSuite(undefined)).toThrow('formato inesperado')
    })
  })

  describe('generate evaluations object', () => {
    test('Validates generation of evaluation objects', () => {
      let input = [
        {
          name: 'addition_isIcorrect',
          classname: 'com.example.myapplication_teste.ExampleUnitTest',
          time: '0.004',
          failures: [
            {
              message: 'java.lang.AssertionError: expected:<7> but was:<8>',
              type: 'java.lang.AssertionError'
            },
            {
              message: 'java.lang.AssertionError: expected:<7> but was:<8>',
              type: 'java.lang.AssertionError'
            }
          ]
        },
        {
          name: 'addition_isCorrect',
          classname: 'com.example.myapplication_teste.ExampleUnitTest',
          time: '0.0',
          failures: []
        }
      ]

      expect(generateEvaluations(input)).toEqual( [
        { grade: 1, description: 'addition_isIcorrect' },
        { grade: 3, description: 'addition_isCorrect' }])
    })
  })

  describe('runStepsEvaluator', () => {
    beforeEach(() => {
      jest.spyOn(core, 'info').mockImplementation(() => {})
      jest.spyOn(core, 'setOutput').mockImplementation(() => {})
      jest.spyOn(core, 'setFailed').mockImplementation(() => {})
      process.env.INPUT_PR_AUTHOR_USERNAME = 'student'
    })

    afterEach(() => {
      jest.restoreAllMocks()
      delete process.env.INPUT_PR_AUTHOR_USERNAME
    })

    test('xml with testcases must generate the result output', () => {
      runStepsEvaluator(['./src/test/res/exemplo1/'])

      expect(core.setFailed).not.toHaveBeenCalled()
      expect(core.setOutput).toHaveBeenCalledWith('result', expect.any(String))
    })

    test('xml generated by a crashed run (testsuite without testcases) must fail with a clear infrastructure error', () => {
      runStepsEvaluator(['./src/test/res/exemplo4/instrumented/'])

      expect(core.setOutput).not.toHaveBeenCalled()
      expect(core.setFailed).toHaveBeenCalledWith(expect.stringContaining('sem nenhum <testcase>'))
    })
  })
})
