name: 'JUnit evaluator kotlin'
description: 'JUnit  Kotlin evaluator  action for Tryber projects in android'
inputs:
  pr_author_username: 
    description: "Pull Request author username"
    required: true

outputs:
  result: 
    description: 'JUnit unit tests JSON results in base64 format'
