name: 'JUnit evaluator'
description: 'JUnit evaluator  action for Tryber projects in android'
inputs:
  pr_author_username:
    description: 'Pull Request author username'
    required: true
  test-path: 
    description: "Path to the test directory"
    required: false
  unit-test-output:
    description: "Output from unit tests"
    required: false
  instrumented-test-output:
    description: "Output from instrumented tests"
    required: false

outputs:
  result: 
    description: 'JUnit unit tests JSON results in base64 format'
runs:
  using: 'node16'
  main: 'dist/index.js'
