name: "JUnit evaluator"
description: "JUnit evaluator for Tryber projects in android"
inputs:
  unit_test:
    description: "Unit test"
    required: false
    default: "true"
  instrumented_test:
    description: "Instrumented_test test"
    required: false
    default: "false"
  pr_author_username:
    description: "Pull Request author username"
    required: true

outputs:
  result:
    description: "JUnit unit tests JSON results in base64 format"
    value: ${{ steps.get_junit_results.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Set up Nodejs 18
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17"

    - name: Gradle cache
      uses: gradle/gradle-build-action@v2

    - name: Run Unit tests
      if: ${{ inputs.unit_test == 'true' }}
      run: ./gradlew test
      shell: bash
      continue-on-error: true

    - name: Enable KVM group perms
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Run Instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      if: ${{ inputs.instrumented_test == 'true' }}
      continue-on-error: true
      with:
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        api-level: 29
        script: ./gradlew connectedCheck

    - name: Get JUnit results
      id: get_junit_results
      run: node $GITHUB_ACTION_PATH/dist/index.js
      shell: bash
      env:
        INPUT_PR_AUTHOR_USERNAME: ${{inputs.pr_author_username}}
