name: "JUnit evaluator"
description: "JUnit evaluator for Tryber projects in android"
inputs:
  unit_test:
    description: "Unit test"
    required: false
    default: "true"
  instrumented_test:
    description: "Instrumented_test test"
    required: false
    default: "false"
  pr_author_username:
    description: "Pull Request author username"
    required: true

outputs:
  result:
    description: "JUnit unit tests JSON results in base64 format"
    value: ${{ steps.get_junit_results.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Set up Nodejs 16
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17"

    - name: Gradle cache
      uses: gradle/gradle-build-action@v2

    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-29

    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: Run Unit tests
      if: ${{ inputs.unit_test == 'true' }}
      run: ./gradlew test
      shell: bash

    - name: Run Instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      if: ${{ inputs.instrumented_test == 'true' }}
      with:
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        api-level: 29
        script: ./gradlew connectedCheck

    - name: Get JUnit results
      id: get_junit_results
      run: node $GITHUB_ACTION_PATH/dist/index.js
      shell: bash
      env:
        INPUT_PR_AUTHOR_USERNAME: ${{inputs.pr_author_username}}
