name: 'JUnit evaluator'
description: 'JUnit evaluator  action for Tryber projects in android'
inputs:
  test-path: 
    description: "Path to the test directory"
    required: true

outputs:
  result: 
    description: 'JUnit unit tests JSON results in base64 format'
runs:
  using: 'node16'
  main: 'index.js'
