name: 'JUnit evaluator'
description: 'JUnit evaluator  action for Tryber projects in android'
inputs:
  unit_test:
    description: 'Unit test'
    required: false
    default: 'true'
  instrumented_test:
    description: 'Instrumented_test test'
    required: false
    default: 'false'
  pr_author_username:
    description: 'Pull Request author username'
    required: true

outputs:
  result: 
    description: 'JUnit unit tests JSON results in base64 format'
runs:
  using: 'composite'
  steps:
      - name: View PR author
        run: echo "This PR is opened by ${{ inputs.pr_author_username }} ."
      - name: Print Input github username
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Set up Nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Run Unit tests
        if: ${{ inputs.unit_test == 'true' }} 
        run: ./gradlew test
        shell: bash

      - name: Run Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        if: ${{ inputs.instrumented_test == 'true' }}
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Get JUnit results
        run: node $GITHUB_ACTION_PATH/dist/index.js
        shell: bash